CREATE SCHEMA cars;
USE cars;
-- READ DATA --
SELECT *
FROM car_dekho;
-- TOTAL CARS -- 
SELECT COUNT(*) 
FROM car_dekho;
-- CARS AVAILABLE IN 2023 --
SELECT COUNT(*)
FROM car_dekho 
WHERE YEAR = 2023;
-- CARS AVAILABLE IN 2020,2021,2022 --
SELECT COUNT(*) 
FROM car_dekho 
WHERE YEAR IN (2020,2021,2022) GROUP BY YEAR;
-- TOTAL CARS BY YEARS --
SELECT YEAR, COUNT(*) 
FROM car_dekho 
GROUP BY YEAR;
-- TOTAL DIESEL CARS IN 2020 --
SELECT COUNT(*)
FROM car_dekho
WHERE YEAR = 2020 
AND FUEL = "Diesel";
-- TOTAL PETROL CARS IN 2021 --
SELECT COUNT(*)
FROM car_dekho
WHERE YEAR = 2021 
AND FUEL = "Petrol";
-- ALL TYPES OF FUEL CAR BY ALL YEARS --
SELECT YEAR, COUNT(*)
FROM car_dekho
WHERE FUEL = "Petrol"
GROUP BY YEAR;
SELECT YEAR, COUNT(*)
FROM car_dekho
WHERE FUEL = "Diesel"
GROUP BY YEAR;
SELECT YEAR, COUNT(*)
FROM car_dekho
WHERE FUEL = "CNG"
GROUP BY YEAR;
-- IN WHICH YEAR THERE ARE MORE THAN 100 CARS AVAILABLE --
SELECT YEAR, COUNT(*)
FROM car_dekho
GROUP BY YEAR HAVING COUNT(*)>100;
-- TOTAL CARS BETWEEN 2015 AND 2023 -- 
SELECT COUNT(*)
FROM car_dekho
WHERE YEAR BETWEEN 2015 AND 2023;
-- DETAILS OF CARS AVAILABLE BETWEEN 2015 AND 2023 --
SELECT *
FROM car_dekho
WHERE YEAR BETWEEN 2015 AND 2023;
